name: ci
on:
  pull_request:
  push:
    branches:
    - master
  schedule:
  - cron: '00 01 * * *'

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }} 
    env:
      CARGO: cargo
      TARGET:
      FEATURES:
    strategy:
      fail-fast: false
      matrix:
        build:
        - stable
        - collectd-head
        - bindgen
        - aarch64
        - regen
        include:
        - build: stable
          os: 'ubuntu-latest'
        - build: collectd-head
          os: 'ubuntu-latest'
        - build: bindgen
          os: 'ubuntu-18.04'
        - build: aarch64
          target: aarch64-unknown-linux-gnu
          os: 'ubuntu-latest'
        - build: regen
          os: 'ubuntu-latest'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Use Cross
      if: matrix.build == 'aarch64'
      run: |
        cargo install cross
        echo "CARGO=cross" >> $GITHUB_ENV
        echo "TARGET=--target ${{ matrix.target }}" >> $GITHUB_ENV
      
    - name: regenerate-bindings
      if: matrix.build == 'regen'
      run: ./regenerate-bindings.sh

    - name: collectd-head
      if: matrix.build == 'collectd-head'
      run: |
        git clone https://github.com/collectd/collectd /tmp/collectd
        echo "COLLECTD_PATH=/tmp/collectd" >> $GITHUB_ENV
        echo "FEATURES=--features bindgen" >> $GITHUB_ENV
  
    - name: bindgen
      if: matrix.build == 'bindgen'
      run: |
        sudo apt-get install -y --no-install-recommends collectd collectd-dev
        echo "FEATURES=--features bindgen" >> $GITHUB_ENV

    - name: tests
      run: ${{ env.CARGO }} test $FEATURES --verbose $TARGET

    - name: test benchmarks
      if: matrix.build == 'stable'
      run: |
        cargo bench --no-run --features stub
